/*
 * This source file was generated by the Gradle 'init' task
 */
package test2;

import test2.calulator.adder.*;
import test2.calulator.divider.*;
import test2.calulator.flipper.*;
import test2.calulator.multiplier.*;
import test2.calulator.substractor.*;

public class App {
    public static void main(String[] args) {
        IAdder adder = new Adder();
        IFlipper flipper = new Flipper();
        ISubstractor substractor = new Substractor(adder, flipper);
        IMultiplier multiplier = new Multiplier(adder, flipper);
        IDivider divider = new Divider(multiplier, substractor);

        System.out.println(divider.divide(10, -1));
    }
}
